---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pranavdhopey/Sample-Helm-Chart.git
    targetRevision: HEAD
    path: ApplicationSets/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
