{{- if .Values.externalsecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  {{.Values.externalsecret.name}}
  namespace: {{ .Values.externalsecret.namespace }}
  labels:
    {{- toYaml .Values.externalsecret.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.externalsecret.annotations | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalsecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalsecret.secretStoreRef.name }}
    kind: {{ .Values.externalsecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalsecret.target.name }} #secret_to_be_created in k8s
    creationPolicy: {{ .Values.externalsecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalsecret.target.deletionPolicy }}
    template:
      type: {{ .target.type | default "Opaque" }}    
  data:
  {{- toYaml .Values.externalsecret.data | nindent 4 }}
{{- end }}
