{{- if .Values.secretstore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretstore.name }}
  namespace: {{ .Values.secretstore.namespace }}
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.secretstore.clusterLocation }}
          clusterName: {{ .Values.secretstore.clusterName }}
          serviceAccountRef:
            name: {{ .Values.secretstore.serviceAccountRef.name }}
      projectID: {{ .Values.secretstore.projectID }}
{{- end }}
