apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - ./argoapp/

helmCharts:
- name: argoapp
  repo: https://pranavdhopey.github.io/Sample-Helm-Chart/
  version: 0.2.0
  releaseName: my-app
  namespace: my-app
  valuesFile: ./argoapp/values.yaml
- name: ingress
  repo: https://pranavdhopey.github.io/Sample-Helm-Chart/
  version: 0.1.0
  releaseName: my-app
  namespace: my-app
  valuesFile: ./ingress/values.yaml  

configMapGenerator:
- name: my-app-argoapp-configmap
  # behavior: merge
  # literals:
  # - HOST_DNS="http://argoapp.goinit.net/"
  # - ENV="prod"
  # - ENV_TYPE="prod"
  files: 
  - ./argoapp/config/preview-env.yaml   

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml