apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - .

helmCharts:
- name: argoapp
  version: 0.1.0
  releaseName: my-app
  namespace: my-app
  valuesFile: ./values.yaml

configMapGenerator:
- name: my-app-configs
  literals:
  - HOST_DNS="http://argoapp-preview.goinit.net/"
  - ENV="preview"
  - ENV_TYPE="non-prod"