apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - ./argoapp/

helmCharts:
- name: argoapp
  repo: https://pranavdhopey.github.io/Sample-Helm-Chart/
  version: 0.1.0
  releaseName: my-app
  namespace: my-app
  valuesFile: ./argoapp/values.yaml

configMapGenerator:
- name: my-app-argoapp-configmap
  literals:
  - HOST_DNS="http://argoapp-preview.goinit.net/"
  - ENV="preview"
  - ENV_TYPE="non-prod"