apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp
  namespace: pranav
spec:
  generators:
  - list:
      elements:
      - cluster: test
        url: https://kubernetes.default.svc
    
  template:
    metadata:
      name: '{{cluster}}-sampleapp'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/pranavdhopey/Sample-Helm-Chart.git'
          targetRevision: main
          path: SampleApp/
          helm:
            releaseName: sampleapp
            valueFiles:
            - dev-values.yaml  
      destination:
        server: '{{url}}'
        namespace: pranav-app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        # automated: 
        #    prune: true 
        #    selfHeal: true 
    
