apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.backendConfig.name }}
spec:
  {{- if .Values.backendConfig.iap.enabled }}
  iap:
    enabled: true
    {{- with .Values.backendConfig.iap.oauthclientCredentials }}
    oauthclientCredentials:
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  healthCheck:
    checkIntervalSec: {{ .Values.backendConfig.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.backendConfig.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.backendConfig.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.backendConfig.healthCheck.unhealthyThreshold }}
    type: {{ .Values.backendConfig.healthCheck.type }}
    requestPath: {{ .Values.backendConfig.healthCheck.requestPath }}
    port: {{ .Values.backendConfig.healthCheck.port }}

{{- if .Values.backendConfig.securityPolicyName }}
  securityPolicy:
    name: {{ .Values.backendConfig.securityPolicyName }}
{{- end }}
