{{- if .Values.previewservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argoapp.fullname" . }}-preview
  labels:
    {{- include "argoapp.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }} 
  annotations:
    {{- toYaml .Values.previewservice.annotations | nindent 4 }}
spec:
  type: {{ .Values.previewservice.type }}
  ports:
    - port: {{ .Values.previewservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argoapp.selectorLabels" . | nindent 4 }}
    {{- with .Values.selectorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}  
{{- end }}    