apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store
  namespace: external-secret
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: asia-south1-a	
          clusterName: pranav-cluster
          serviceAccountRef:
            name: external-secret
      projectID: umesh-ai

