apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
spec:
  destination:
    namespace: external-secret
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-secrets
    helm:
      parameters:
      - name: certController.fullnameOverride
        value: external-secret
      - name: fullnameOverride
        value: external-secret
      - name: webhook.fullnameOverride
        value: external-secret
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.15.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

