{{- if .Values.Rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app1.selectorLabels" . | nindent 6 }}  
  strategy:
    blueGreen: 
      activeService: {{ include "app1.fullname" . }}
      previewService: {{ include "app1.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.Rollout.autoPromotionEnabled }}     
      scaleDownDelaySeconds: {{ .Values.Rollout.scaleDownDelaySeconds }}   
      activeMetadata:
        labels:
          role: active
      previewMetadata:
        labels:
          role: preview   
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app1.selectorLabels" . | nindent 8 }}
        {{- with .Values.selectorLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}            
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app1.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.EnvVars }}
          env:
          {{- range .Values.EnvVars }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          {{- end }}   
          {{- if .Values.configMapData }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapData.name }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}   
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.volumes | default "" | nindent 8 }}
{{- end }}      
