secretstore:
  enabled: true
  name: sampleapp-secret-store
  clusterLocation: asia-south1-a
  clusterName: pranav-cluster
  serviceAccountRef:
    name: sampleapp
  projectID: umesh-ai

externalsecret:
  enabled: true
  name: sampleapp-external-secret
  labels: {}
  annotations: {}
  refreshInterval: "1m"
  secretStoreRef:
    name: sampleapp-secret-store
    kind: SecretStore
  target:
    name: sampleapp-k8s-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: external-secret
        version: latest
        property: DB_USERNAME
        decodingStrategy: None  # None, Base64, Base64URL, Auto
    - secretKey: DB_PASSWORD
      remoteRef:
        key: external-secret
        version: latest
        property: DB_PASSWORD
        decodingStrategy: None  # None, Base64, Base64URL, Auto    

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: external-sa@umesh-ai.iam.gserviceaccount.com
  labels:
    app: sampleapp
  name: "sampleapp"

jobs:
  - name: test-cronjob
    enabled: true
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 5
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    serviceAccount: sampleapp 
    schedule: "0 * * * *"
    timeZone: ""
    suspend: false
    image:
      repository: alpine
      tag: latest
      imagePullPolicy: IfNotPresent
    labels:
      app: cron
      env: dev
    podSecurityContext:
      runAsNonRoot: true  # Ensures the container runs as a non-root user
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault  # Enforces the default seccomp profile for better security
    securityContext:
      allowPrivilegeEscalation: false  # Ensures no privilege escalation
      capabilities:
        drop:
          - "ALL"  # Drop all Linux capabilities to comply with the restricted policy
    env: 
    command: ["/bin/sh", "-c"]
    args:
      - echo "hello"

managedCertificateEnabled: true
managedCertificate:
  - name: sampleapp1-certificate
    domains: 
    - app1-dev.goinit.net
  - name: sampleapp2-certificate
    domains: 
    - app2-dev.goinit.net  

frontendConfigEnabled: true
frontendConfig:
  name: sampleapp-frontend-config
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  # sslPolicy: gke-ingress-ssl-policy

ingress:
  enabled: true
  name: sampleapp-ingress
  className: ""
  annotations: 
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: 'true'
    networking.gke.io/managed-certificates: "sampleapp1-certificate,sampleapp2-certificate" 
    networking.gke.io/v1beta1.FrontendConfig: "sampleapp-frontend-config"
    # kubernetes.io/ingress.global-static-ip-name: "my-static-address"
  hosts:
    - host: app1-dev.goinit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app1-service
                port:
                  number: 80
    - host: app2-dev.goinit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app2-service
                port: 
                  number: 80

internal_ingress:
  enabled: false
  name: sampleapp-internal-ingress
  className: ""
  annotations: 
    kubernetes.io/ingress.class: gce-internal
    # kubernetes.io/ingress.regional-static-ip-name: "my-static-address"
  hosts:
    - host: app1.goinit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app1-service
                port:
                  number: 80
    - host: app2.goinit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app2-service
                port: 
                  number: 80

sample-app1:
  enabled: true   
  app:
    name: sample-app1
    replicaCount: 1
    image:
      repository: httpd 
      pullPolicy: IfNotPresent
      tag: "alpine"
    containerPort: 80  
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    labels: 
      env: dev
      app: sample-app1
    podAnnotations: {}
    podSecurityContext: {}
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000  
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3     
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3   
    nodeSelector: {}
    tolerations: []
    affinity: {}
    volumes: []
    volumeMounts: [] 
  serviceAccount:
    create: false
    annotations: {}
    name: "sampleapp"
  service:
    name: sample-app1-service
    labels: 
      env: dev
      app: sample-app1
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations:  
      cloud.google.com/backend-config: '{"default": "sample-app1-backendconfig"}'
      cloud.google.com/neg: '{"ingress": true}'
  backendConfig:
    name: sample-app1-backendconfig
    iap:
      enabled: false
      oauthclientCredentials:
        secretName: app1-iap-secret
    healthCheck:
      checkIntervalSec: 5
      timeoutSec: 5
      healthyThreshold: 2
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /
      port: 80
    # securityPolicyName: "example-security-policy"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  pdb:
    enabled: false
    maxUnavailable: 1
  env: []
    # - name: HOST_DNS
    #   value: http://app1.goinit.net/ 
  envFromSecrets:
    - name: DB_USERNAME
      secretName: sampleapp-k8s-secret
      secretKey: DB_USERNAME
    - name: DB_PASSWORD
      secretName: sampleapp-k8s-secret
      secretKey: DB_PASSWORD  

sample-app2:
  enabled: true  
  app:
    name: sample-app2
    replicaCount: 1
    image:
      repository: nginx 
      pullPolicy: IfNotPresent
      tag: "alpine"
    containerPort: 80  
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    labels: 
      env: dev
      app: sample-app2
    podAnnotations: {}
    podSecurityContext: {}
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3     
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    nodeSelector: {}
    tolerations: []
    affinity: {}  
    volumes: []
    volumeMounts: []   
  serviceAccount:
    create: false
    annotations: {}
    name: "sampleapp"
  service:
    name: sample-app2-service
    labels: 
      env: dev
      app: sample-app2
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations:  
      cloud.google.com/backend-config: '{"default": "sample-app2-backendconfig"}'
      cloud.google.com/neg: '{"ingress": true}'
  backendConfig:
    name: sample-app2-backendconfig
    iap:
      enabled: false
      oauthclientCredentials:
        secretName: app2-iap-secret
    healthCheck:
      checkIntervalSec: 5
      timeoutSec: 5
      healthyThreshold: 2
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /
      port: 80
  #securityPolicyName: "example-security-policy"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  pdb:
    enabled: false
    maxUnavailable: 1
  env: []
    # - name: HOST_DNS
    #   value: http://argoapp.goinit.net/ 
  envFromSecrets: []
    # - name: DB_USERNAME
    #   secretName: k8s-secret
    #   secretKey: DB_USERNAME

