app1:
  enabled: true   

app2:
  enabled: true  

serviceAccount:
  create: true
  annotations: 
    iam.gke.io/gcp-service-account: cloudtaskumesh@umesh-dev-gcp-412809.iam.gserviceaccount.com	
  name: "sampleapp"

configMapData: 
  name: sampleapp-configmap
  data: 
    HOST_DNS: "http://sampleapp.goinit.net/"
    ENV: "prod"
    ENV_TYPE: "prod"

configMapDataPreview:
  name: sampleapp-preview-configmap
  data:
    HOST_DNS: "http://sampleapp-preview.goinit.net/"
    ENV: "prod-preview"
    ENV_TYPE: "prod-preview"  

managedCertificateEnabled: false
managedCertificate:
  name: sampleapp-certificate
  domains: 
    - app1-dev.goinit.net
    - app2-dev.goinit.net

frontendConfigEnabled: false
frontendConfig:
  name: sampleapp-frontend-config
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  # sslPolicy: gke-ingress-ssl-policy

ingress:
  enabled: false
  name: sampleapp-ingress
  className: ""
  annotations: 
    kubernetes.io/ingress.class: gce
    # networking.gke.io/managed-certificates: "hello-apps-certificate" 
    # networking.gke.io/v1beta1.FrontendConfig: "hello-apps-frontend-config"
  hosts:
    - host: app1-dev.goinit.net
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: sampleapp-app1
                port:
                  number: 80
    - host: app2-dev.goinit.net
      http:
        paths:
          - path: /app2
            pathType: Prefix
            backend:
              service:
                name: sampleapp-app2
                port: 
                  number: 80
