apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: argo
        url: https://kubernetes.default.svc
    
  template:
    metadata:
      name: '{{cluster}}-sampleapp-stage'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/pranavdhopey/Sample-Helm-Chart.git'
          targetRevision: main
          path: SampleApp/
          helm:
            releaseName: sampleapp
            valueFiles:
            - values-stage.yaml  
      destination:
        server: '{{url}}'
        namespace: pranav-stage
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        # automated: 
        #    prune: true 
        #    selfHeal: true 
    
