managedCertificateEnabled: false
managedCertificates:
  - name: argoapp-preview-certificate
    domains: 
    - argoapp-preview.goinit.net

frontendConfigEnabled: false
frontendConfig:
  name: argoapp-preview-frontend-config
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  # sslPolicy: gke-ingress-ssl-policy

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    # networking.gke.io/managed-certificates: "argoapp-preview-certificate" 
    # networking.gke.io/v1beta1.FrontendConfig: argoapp-preview-frontend-config"
  hosts:
    - host: argoapp-preview.goinit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argoapp-preview
                port: 
                  number: 80 
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local


