# Default values for argoapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  image:
    repository: nginx 
    pullPolicy: IfNotPresent
    tag: "alpine"
  containerPort: 80  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  labels: 
    env: dev
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3     
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  nodeSelector: {}
  tolerations: []
  affinity: {}  
  volumes: []
  # - name: podinfo
  #   downwardAPI:
  #     items:
  #     - path: "labels"
  #       fieldRef:
  #         fieldPath: metadata.labels
  volumeMounts: []
  # - name: podinfo
  #   mountPath: /etc/podinfo    

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  name: sample-app2-service
  type: ClusterIP
  targetPort: 80
  annotations:  
    cloud.google.com/backend-config: '{"default": "sample-app2-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'

backendConfig:
  name: sample-app2-backendconfig
  iap:
    enabled: false
    oauthclientCredentials:
      secretName: app2-iap-secret
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80
 #securityPolicyName: "example-security-policy"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

pdb:
  enabled: false
  maxUnavailable: 1

env: []
  # - name: HOST_DNS
  #   value: http://argoapp.goinit.net/ 

envFromSecrets: []
  # - name: DB_USERNAME
  #   secretName: k8s-secret
  #   secretKey: DB_USERNAME